#993 Feature to import / export Project - crash data is skipped in se…
SCADA-LTS/Scada-LTS pull request #1540
Opened 2021-02-16 18:01 UTC by Limraj

…rialization, error logging, correct create temp file

2021-02-17 07:57 UTC, SoftQ commented on src/com/serotonin/mango/rt/event/type/DataSourceEventType.java
> +            LOG.error("DataSource for id: " + dataSourceId + " is not exists.");
typo - "does not exist"

2021-02-17 08:00 UTC, SoftQ requested changes
please correct a typo :)

2021-02-17 09:21 UTC, Limraj commented
The changes will still be tested.

2021-02-17 13:33 UTC, fabiodurao commented
The export / import tool in .zip had some problems since version 1.0 of ScadaBR and remained the same in ScadaBR 1.1 (original ScadaLTS branch). The export tool in .json has a user related problem that only appeared in ScadaBR 1.1, this is probably related to the addition of user profiles that did not exist in ScadaBR 1.0.

2021-02-17 14:58 UTC, Limraj commented
Hi @fabiodurao
has the problem you write about already described somewhere? I would be interested in the error scenario. I am happy to check if this problem occurs in the current version of the application. If the scenario has not been described yet, please create an issue. It is particularly interesting how the error manifested itself and with which function it was related to "Generate JSON" or "Export Project". 

This patch relates with bug where "Export Project" was interrupted before the process was terminated, we started the export which stopped without generate zip file.
Export crashes by incorrect data in eventhandlers, and problem with create temp file and permissions.
This patch will fix it.

![export2](https://user-images.githubusercontent.com/35842300/108218252-c0b11180-7134-11eb-952a-fa54782d7b23.png)

We have two places related to data export, this function is marked in red and green. The relationship between these functions is as follows, "Export Project" (green) uses the same mechanism to serialize data as the "Generate JSON" function, i.e. problems occurring with the "Generate JSON" function will appear in the "Export Project" function, while the "Export Project "may have bugs that arae not related to "Generate JSON". Generally "Export Project" is "Generate JSON" with all checkboxes checked, with the option to add images(graphical view), and description with app version.

Greets,
Kamil Jarmusik

2021-02-25 12:08 UTC, Limraj commented
This topic only fix export and added api to export.

2021-02-26 05:52 UTC, grzesiekb commented
Please add a branch to Travis so that it builds a branch with your task and creates a docker to test

2021-02-26 13:42 UTC, grzesiekb commented
The data is exported even with a large database from a docker with tag 993. I understand that this task only includes improving the export of the project (without import). Therefore I give that it is ok.

2021-02-26 13:44 UTC, grzesiekb approved these changes

2021-03-02 13:33 UTC, arturro96 approved these changes

2021-03-11 15:36 UTC, merged