#1674 Fix for anonymous access for simple point and simple compound
SCADA-LTS/Scada-LTS pull request #1675
Opened 2021-05-04 11:57 UTC by Limraj

2021-05-06 13:16 UTC, SoftQ approved these changes
accepted as a temporary solution. All anonymous methods should be refactored after deployment of Spring Security with support for anonymous access.

2021-05-07 12:20 UTC, arturro96 approved these changes

2021-05-17 15:58 UTC, arturro96 commented on src/org/scada_lts/dao/migration/mysql/V2_7__AnonymousUser.java
> +public class V2_7__AnonymousUser extends BaseJavaMigration {
I would change the name to V2_7__ to avoid conflicts with other branches that have migration and will be merged in version 2.7

2021-05-20 14:33 UTC, arturro96 approved these changes

2021-05-31 14:27 UTC, radek2s requested changes

2021-05-31 14:27 UTC, radek2s commented on src/org/scada_lts/dao/migration/mysql/V2_7_0_3__AnonymousUser.java
> +                    "null@sivec.lu",
It must not contain any own name. Try to use "anonymous@mail.com" instead.

2021-06-07 09:44 UTC, radek2s approved these changes

2021-06-09 08:49 UTC, merged