Feature/#1702 new user parameters
SCADA-LTS/Scada-LTS pull request #1706
Opened 2021-05-20 12:31 UTC by arturro96

2021-05-24 11:51 UTC, radek2s approved these changes

2021-05-24 12:34 UTC, sselvaggi requested changes

2021-05-24 12:34 UTC, sselvaggi commented on WebContent/WEB-INF/jsp/users.jsp
> +            <tr id="hideMenuRow" style="display:none;">
reemplace style="display:none" by class="hidden"

and add theese to the most global stylesheet possible

.hidden { display:none; }
.hidden-important { display:none!important; }

2021-05-24 12:52 UTC, sselvaggi commented on WebContent/WEB-INF/jsp/users.jsp
> +        console.log(user);
remove console.log

2021-05-25 13:17 UTC, sselvaggi approved these changes

2021-05-25 15:06 UTC, Limraj approved these changes

2021-05-31 11:09 UTC, merged