Point hierarchy 2.0 Vue.js page
SCADA-LTS/Scada-LTS pull request #1975
Opened 2021-12-07 14:20 UTC by radek2s

Improved point hierarchy page.

2021-12-10 06:38 UTC, grzesiekb approved these changes

2021-12-15 11:09 UTC, grzesiekb approved these changes

2021-12-20 12:31 UTC, sselvaggi requested changes

2021-12-20 12:31 UTC, sselvaggi commented on scadalts-ui/src/store/pointHierarchy/index.js
> +export function searchFolderInHierarchy(array, folderId, debug=false) {
I think it'd be better to name array param as datapoints and replace for by for of loop

2021-12-20 13:36 UTC, sselvaggi approved these changes

2021-12-20 13:45 UTC, merged